### PR TITLE
FIX #63: regression by pt2to3 tool miss-converting create_index()

### LINKED ISSUE #63: Problem on Windows/PyQt5.8.2, trying master tree (since Qt5 merge)
launching via
````
vitables -v 2 -l "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\notebooks\vit.log"
````

I fall on this error:
````
2017-04-30 12:49:27,400 - vitables - ERROR -   File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\Scripts\vitables-script.pyw", line 11, in <module>
    load_entry_point('ViTables==2.2.1.dev0', 'gui_scripts', 'vitables')()
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\vitables-2.2.1.dev0-py3.6.egg\vitables\start.py", line 180, in gui
    vtapp = VTApp(mode=args.mode, dblist=args.dblist, h5files=args.h5file)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\vitables-2.2.1.dev0-py3.6.egg\vitables\vtapp.py", line 132, in __init__
    self.gui = vtgui.VTGUI(self, vtconfig.getVersion())
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\vitables-2.2.1.dev0-py3.6.egg\vitables\vtgui.py", line 79, in __init__
    self.setup(vtapp)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\vitables-2.2.1.dev0-py3.6.egg\vitables\vtgui.py", line 87, in setup
    self.dbs_tree_model =  dbstreemodel.DBsTreeModel(self, vtapp)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\vitables-2.2.1.dev0-py3.6.egg\vitables\h5db\dbstreemodel.py", line 102, in __init__
    self.tmp_dbdoc = self.__createTempDB()
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\vitables-2.2.1.dev0-py3.6.egg\vitables\h5db\dbstreemodel.py", line 324, in __createTempDB
    db_doc = self.createDBDoc(self.tmp_filepath, True)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\vitables-2.2.1.dev0-py3.6.egg\vitables\h5db\dbstreemodel.py", line 304, in createDBDoc
    self.insertRows(0, 1)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\vitables-2.2.1.dev0-py3.6.egg\vitables\h5db\dbstreemodel.py", line 1027, in insertRows
    top_left = self.index(first, 0, parent)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\vitables-2.2.1.dev0-py3.6.egg\vitables\h5db\dbstreemodel.py", line 915, in index
    return self.create_index(row, column, node)
'DBsTreeModel' object has no attribute 'create_index'
````

### PR DESCRIPTION
**Pull request by ankostis**
Revert regression by ff0555c where `pt2to3` tool miss-detected `DBsTreeModel.createIndex()` as belonging to *tables* API, and converting it to create_index().

### CODE REVIEW

**Comment by stonebig** [comment]
yes ! Now the GUI is working on my pc. 

vitables01
